// Yetkilendirme modülleri - CustomRole modal ve Yetkiler tab için kullanılır
module.exports = {
  MODULES: {
    report: { label: "Raporlar", resource: "report" },
    bank: { label: "Banka Bilgileri", resource: "bank" },
    authorization: { label: "Yetkilendirme", resource: "authorization" },
    pricing: { label: "Fiyatlandirma", resource: "pricing" },
    approval: { label: "Onay Yönetimi", resource: "approval" },
    note: { label: "Is Emri", resource: "note" },
    calendar: { label: "Takvim", resource: "event" },
    message: { label: "Mesajlar", resource: "message" },
  },
  ACTIONS: [
    { action: "view", label: "Görüntüleme" },
    { action: "create", label: "Oluşturma" },
    { action: "update", label: "Güncelleme" },
    { action: "delete", label: "Silme" },
    { action: "manage", label: "Yönetim" },
  ],
  PERMISSION_LABELS: {
    "report:report:view": "Rapor Görüntüleme",
    "report:report:create": "Rapor Oluşturma",
    "report:report:update": "Rapor Güncelleme",
    "report:report:delete": "Rapor Silme",
    "report:report:manage": "Rapor Yönetim",
    "bank:bank:view": "Banka Bilgileri Görüntüleme",
    "bank:bank:create": "Banka Bilgileri Oluşturma",
    "bank:bank:update": "Banka Bilgileri Güncelleme",
    "bank:bank:delete": "Banka Bilgileri Silme",
    "bank:bank:manage": "Banka Bilgileri Yönetim",
    "authorization:authorization:view": "Yetkilendirme Görüntüleme",
    "authorization:authorization:create": "Yetkilendirme Oluşturma",
    "authorization:authorization:update": "Yetkilendirme Güncelleme",
    "authorization:authorization:delete": "Yetkilendirme Silme",
    "authorization:authorization:manage": "Yetkilendirme Yönetim",
    "pricing:pricing:view": "Fiyatlandirma Görüntüleme",
    "pricing:pricing:create": "Fiyatlandirma Oluşturma",
    "pricing:pricing:update": "Fiyatlandirma Güncelleme",
    "pricing:pricing:delete": "Fiyatlandirma Silme",
    "pricing:pricing:manage": "Fiyatlandirma Yönetim",
    "approval:approval:view": "Onay Yönetimi Görüntüleme",
    "approval:approval:create": "Onay Yönetimi Oluşturma",
    "approval:approval:update": "Onay Yönetimi Güncelleme",
    "approval:approval:delete": "Onay Yönetimi Silme",
    "approval:approval:manage": "Onay Yönetimi Yönetim",
    "note:note:create": "Not Oluşturma",
    "note:note:view": "Not Görüntüleme",
    "note:note:update": "Not Güncelleme",
    "note:note:delete": "Not Silme",
    "note:note:manage": "Not Yönetim",
    "calendar:event:view": "Takvim Görüntüleme",
    "calendar:event:create": "Takvim Oluşturma",
    "calendar:event:update": "Takvim Güncelleme",
    "calendar:event:delete": "Takvim Silme",
    "calendar:event:manage": "Takvim Yönetim",
    "message:message:view": "Mesajlar Görüntüleme",
    "message:message:create": "Mesajlar Oluşturma",
    "message:message:update": "Mesajlar Güncelleme",
    "message:message:delete": "Mesajlar Silme",
    "message:message:manage": "Mesajlar Yönetim",
  },
};
